# Generated by Django 2.1.7 on 2019-03-30 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('protein', models.CharField(max_length=200)),
                ('num_patties', models.IntegerField(default=1)),
                ('cook', models.IntegerField(choices=[(1, 'Rare'), (2, 'Medium Rare'), (3, 'Medium'), (4, 'Medium Well'), (5, 'Well Done')], default=3)),
                ('lettice', models.BooleanField(default=False)),
                ('tomato', models.BooleanField(default=False)),
                ('onion', models.BooleanField(default=False)),
                ('cheese', models.BooleanField(default=False)),
                ('bun', models.CharField(choices=[('Sesame', 'Sesame'), ('Potato', 'Potato'), ('Pretzel', 'Pretzel')], default='Sesame', max_length=7)),
                ('sauce', models.CharField(blank=True, max_length=200)),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
