# Generated by Django 2.1.7 on 2019-03-30 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burgerForm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment2',
        ),
    ]
