# Generated by Django 2.1.7 on 2019-03-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgerForm', '0002_remove_order_comment2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
