# Generated by Django 2.1.7 on 2019-04-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgerForm', '0004_remove_order_comments2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sauce',
            field=models.CharField(choices=[('Ketchup', 'Ketchup'), ('Mustard', 'Mustard'), ('BBQ', 'BBQ'), ('Mayo', 'Mayo')], default=False, max_length=7),
        ),
    ]
